Feature/tw29110559/asset manifest
kanopi/kanopi-pack-asset-loader pull request #7
Opened 2023-04-05 14:48 UTC by miriamgoldman

## Description
> As a developer, I need my Asset Loader to be able to load assets in Production by either filepath or HTTP/HTTPS. I also need my default to be by filepath.

## Affected URL
Local Only

## Related Tickets
https://kanopi.teamwork.com/tasks/29110559

## Steps to Validate
1. Via composer, load `kanopi-pack-aset-loader` using the `feature/tw29110559/asset-manifest` branch, rather than `main`
2. Run `fin production` on your project, and comment out `KANOPI_DEVELOPMENT_ASSET_URL` in your `wp-config.php`
3. Test to make sure your assets are loading
4. In `functions.php`, pass in the stylesheet directory URI for your project to the Loader Configuration. 
5. Verify that assets still load
6. Verify that `fin development` still works, by uncommenting the KANOPI_DEVELOPMENT_ASSET_URL environment variable in `wp-config.php`

## Notes

1. When passing in a URL, we must pass in the path to the stylesheet directory. This should be noted in documentation.
2. If passing in a filepath, such as `get_stylesheet_directory()`, we will need to run a `str_replace` to remove the absolute path, so that `wp_enqueue_scripts/wp_enqueue_styles` can read the file properly. Again, this should be documented.

2023-04-21 13:07 UTC, rleeson requested changes
A few changes, plus review and let me know if you have questions.

2023-04-24 12:39 UTC, miriamgoldman commented on src/Registry/WordPress.php
> +        $this->_production_url = !empty( $_production_url ) ? $_production_url : str_replace( ABSPATH, '/', get_stylesheet_directory() );
Okay - I removed all the additional stuff in AssetLoader, tested, and it still seems to work. Forgive my ignorance, but it does feel like the correct path is being injected here.

2023-04-26 16:12 UTC, rleeson commented
@miriamgoldman I retrofitted the configuration to use a file path for the Asset manifest in Production only. Please test both Dev and Production to make sure it works in a few projects.

2023-04-26 16:16 UTC, rleeson commented
For easy copy/paste, test with `composer require kanopi/pack-asset-loader:dev-feature/tw29110559/asset-manifest`

2023-04-26 16:21 UTC, rleeson approved these changes
This works, however is a workaround to an architectural mismatch with the current state of Kanopi Pack, which assumes the manifest is the source of truth for all assets. It will work here, next version of the Asset Loader needs a redesign.

2023-04-26 19:03 UTC, rleeson commented
Issues with PR branch pulling cached, closing to check in another.

2023-04-26 19:03 UTC, closed without merging